#pragma once
#define COMPARE_rsi(x) x
#define COMPARE_esi(x) x
#define COMPARE_si(x) x
#define COMPARE_sil(x) x
#define COMPARE_rdi(x) x
#define COMPARE_edi(x) x
#define COMPARE_di(x) x
#define COMPARE_dil(x) x
#define COMPARE_rsp(x) x
#define COMPARE_esp(x) x
#define COMPARE_sp(x) x
#define COMPARE_spl(x) x
#define COMPARE_rbp(x) x
#define COMPARE_ebp(x) x
#define COMPARE_bp(x) x
#define COMPARE_bpl(x) x
#define COMPARE_rax(x) x
#define COMPARE_eax(x) x
#define COMPARE_ax(x) x
#define COMPARE_ah(x) x
#define COMPARE_al(x) x
#define COMPARE_rbx(x) x
#define COMPARE_ebx(x) x
#define COMPARE_bx(x) x
#define COMPARE_bh(x) x
#define COMPARE_bl(x) x
#define COMPARE_rcx(x) x
#define COMPARE_ecx(x) x
#define COMPARE_cx(x) x
#define COMPARE_ch(x) x
#define COMPARE_cl(x) x
#define COMPARE_rdx(x) x
#define COMPARE_edx(x) x
#define COMPARE_dx(x) x
#define COMPARE_dh(x) x
#define COMPARE_dl(x) x
#define COMPARE_r8(x) x
#define COMPARE_r8d(x) x
#define COMPARE_r8w(x) x
#define COMPARE_r8l(x) x
#define COMPARE_r9(x) x
#define COMPARE_r9d(x) x
#define COMPARE_r9w(x) x
#define COMPARE_r9l(x) x
#define COMPARE_r10(x) x
#define COMPARE_r10d(x) x
#define COMPARE_r10w(x) x
#define COMPARE_r10l(x) x
#define COMPARE_r11(x) x
#define COMPARE_r11d(x) x
#define COMPARE_r11w(x) x
#define COMPARE_r11l(x) x
#define COMPARE_r12(x) x
#define COMPARE_r12d(x) x
#define COMPARE_r12w(x) x
#define COMPARE_r12l(x) x
#define COMPARE_r13(x) x
#define COMPARE_r13d(x) x
#define COMPARE_r13w(x) x
#define COMPARE_r13l(x) x
#define COMPARE_r14(x) x
#define COMPARE_r14d(x) x
#define COMPARE_r14w(x) x
#define COMPARE_r14l(x) x
#define COMPARE_r15(x) x
#define COMPARE_r15d(x) x
#define COMPARE_r15w(x) x
#define COMPARE_r15l(x) x
